services:
  - redis
  - docker
language: java
sudo: false
install: true
jdk: oraclejdk8
script:
  - echo $CODECOV_TOKEN
  - mvn clean package -Dmaven.test.skip=true cobertura:cobertura
before_install:
  - java -version
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
cache:
  directories:
    - .autoconf
    - $HOME/.m2
notifications:
  #Pull Request builds do not trigger email notifications
  #turn off email notifications
  #email: false
  email:
    recipients:
      - fanym@easemob.com
    on_success: never # default: change
    on_failure: always # default: always
