services:
  - redis
  - docker
language: java
sudo: false
install: true
jdk: oraclejdk8
addons:
  coverity_scan:
    project:
      name: "reedF/cloud-micro-service"
      description: "Build submitted via Travis CI"
    notification_email: fanym@easemob.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master
script:
  - mvn clean package -Dmaven.test.skip=true cobertura:cobertura
before_install:
  - java -version
  #coverity_scan
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
cache:
  directories:
    - .autoconf
    - $HOME/.m2
notifications:
  #Pull Request builds do not trigger email notifications
  #turn off email notifications
  #email: false
  email:
    recipients:
      - fanym@easemob.com
    on_success: never # default: change
    on_failure: always # default: always
