---
server:
  port: 8761

spring:
  application:
    name: eureka-service
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888

# vcap是Cloudfoundry提供的命名访问规范，可获取节点实例信息
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/