---
server:
  port: 8090

spring:
  application:
    name: boot-admin-server
#spring boot admin
spring.boot.admin:
  routes:
    endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
  turbine:
    #enabled: false
    clusters: default,C1
    location: micro-dashboard      
#endpoints security      
management.security.enabled: false            


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://192.168.59.103:8761/eureka/
   