server: 
  port: 8761
   
--- 
spring: 
  profiles: eureka
  application:
    name: micro-eureka
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
                  
#eureka vcap是Cloudfoundry提供的命名访问规范，可获取节点实例信息
eureka:
  #server:
  #  enableSelfPreservation: false
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://192.168.59.103:8761/eureka/

 
    