---
server:
  port: 8082

spring:
  application:
    name: eureka-client
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
  zipkin:
    #defult is true,to use zipkin,false:not use
    enabled: true
    baseUrl: http://localhost:9411/ 
  # mq stream format to send trace data 
  rabbitmq:
    addresses: ${RABBIT_HOST:172.28.19.78:5672,172.28.19.80:5672}
  sleuth:
    sampler:
      percentage: 1.0
    # stream format  to send trace msg: enable sleuth.stream to use stream
    # default is true,refer to SleuthStreamAutoConfiguration.java
    stream:
      enabled: false
            
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://192.168.59.103:8762/eureka/

# zipkin properties for ServiceApplication.java to debug when there is no zipkin server
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    #enabled: false      