---
server:
  port: 8080

spring:
  application:
    name: eureka-client
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
  #zipkin
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.59.103 with your zipkin IP address
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0
      
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

# zipkin properties for ServiceApplication.java to debug when there is no zipkin server
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    #enabled: false      