server: 
  port: 8761
  
spring: 
  application:
    name: eureka-server

#eureka backup node
backup: ${backup_node:localhost}

#eureka    
eureka:
  #server:
  #  enableSelfPreservation: false
  instance:
    #hostname: localhost
    #using ip to register not using hostname
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${backup}:${server.port}/eureka/
    